import { addIcon } from "@iconify/vue/dist/offline";

/**
 * 这里存放本地图标，在 src/layout/index.vue 文件中加载，避免在首启动加载
 */

// 本地菜单图标，后端在路由的icon中返回对应的图标字符串并且前端在此处使用addIcon添加即可渲染菜单图标
// import HomeFilled from "@iconify-icons/ep/home-filled";
// import InformationLine from "@iconify-icons/ri/information-line";
// import Lollipop from "@iconify-icons/ep/lollipop";
//
// addIcon("homeFilled", HomeFilled);
// addIcon("informationLine", InformationLine);
// addIcon("lollipop", Lollipop);

// element-plus icon
import Check from "@iconify-icons/ep/check";
import Menu from "@iconify-icons/ep/menu";
import HomeFilled from "@iconify-icons/ep/home-filled";
import SetUp from "@iconify-icons/ep/set-up";
import Edit from "@iconify-icons/ep/edit";
import Setting from "@iconify-icons/ep/setting";
import Lollipop from "@iconify-icons/ep/lollipop";
import Link from "@iconify-icons/ep/link";
import Position from "@iconify-icons/ep/position";
import Histogram from "@iconify-icons/ep/histogram";
import RefreshRight from "@iconify-icons/ep/refresh-right";
import ArrowDown from "@iconify-icons/ep/arrow-down";
import Close from "@iconify-icons/ep/close";
import CloseBold from "@iconify-icons/ep/close-bold";
import Bell from "@iconify-icons/ep/bell";
import Guide from "@iconify-icons/ep/guide";
import Iphone from "@iconify-icons/ep/iphone";
import Location from "@iconify-icons/ep/location";
import Tickets from "@iconify-icons/ep/tickets";
import OfficeBuilding from "@iconify-icons/ep/office-building";
import Notebook from "@iconify-icons/ep/notebook";
import Rank from "@iconify-icons/ep/rank";
import VideoPlay from "@iconify-icons/ep/video-play";
import Monitor from "@iconify-icons/ep/monitor";
import Search from "@iconify-icons/ep/search";
import Refresh from "@iconify-icons/ep/refresh";
import EditPen from "@iconify-icons/ep/edit-pen";
import Delete from "@iconify-icons/ep/delete";
import More from "@iconify-icons/ep/more-filled";
import Top from "@iconify-icons/ep/top";
addIcon("check", Check);
addIcon("menu", Menu);
addIcon("homeFilled", HomeFilled);
addIcon("setUp", SetUp);
addIcon("edit", Edit);
addIcon("setting", Setting);
addIcon("lollipop", Lollipop);
addIcon("link", Link);
addIcon("position", Position);
addIcon("histogram", Histogram);
addIcon("refreshRight", RefreshRight);
addIcon("arrowDown", ArrowDown);
addIcon("close", Close);
addIcon("closeBold", CloseBold);
addIcon("bell", Bell);
addIcon("guide", Guide);
addIcon("iphone", Iphone);
addIcon("location", Location);
addIcon("tickets", Tickets);
addIcon("officeBuilding", OfficeBuilding);
addIcon("notebook", Notebook);
addIcon("videoPlay", VideoPlay);
addIcon("rank", Rank);
addIcon("monitor", Monitor);
addIcon("search", Search);
addIcon("refresh", Refresh);
addIcon("edits", EditPen);
addIcon("delete", Delete);
addIcon("more", More);
addIcon("top", Top);

// remixicon
import ArrowRightSLine from "@iconify-icons/ri/arrow-right-s-line";
import ArrowLeftSLine from "@iconify-icons/ri/arrow-left-s-line";
import LogoutCircleRLine from "@iconify-icons/ri/logout-circle-r-line";
import NodeTree from "@iconify-icons/ri/node-tree";
import UbuntuFill from "@iconify-icons/ri/ubuntu-fill";
import QuestionLine from "@iconify-icons/ri/question-line";
import CheckboxCircleLine from "@iconify-icons/ri/checkbox-circle-line";
import InformationLine from "@iconify-icons/ri/information-line";
import CloseCircleLine from "@iconify-icons/ri/close-circle-line";
import ArrowUpLine from "@iconify-icons/ri/arrow-up-line";
import ArrowDownLine from "@iconify-icons/ri/arrow-down-line";
import Bookmark2Line from "@iconify-icons/ri/bookmark-2-line";
import AddFill from "@iconify-icons/ri/add-circle-line";
import ListCheck from "@iconify-icons/ri/list-check";
import More2Fill from "@iconify-icons/ri/more-2-fill";
import Database from "@iconify-icons/ri/database-2-line";
import Dict from "@iconify-icons/ri/git-repository-line";
import Card from "@iconify-icons/ri/bank-card-line";
import Reset from "@iconify-icons/ri/restart-line";
import Dept from "@iconify-icons/ri/git-branch-line";
import Password from "@iconify-icons/ri/lock-password-line";
import Ppt from "@iconify-icons/ri/file-ppt-2-line";
import TerminalWindowLine from "@iconify-icons/ri/terminal-window-line";
import User from "@iconify-icons/ri/user-3-fill";
import Lock from "@iconify-icons/ri/lock-fill";
import userSettingsFill from "@iconify-icons/ri/user-settings-fill";
import baseStationFill from "@iconify-icons/ri/base-station-fill";
import barricadeLine from "@iconify-icons/ri/barricade-line";
import menuUnfoldFill from "@iconify-icons/ri/menu-unfold-fill";
import lineChartFill from "@iconify-icons/ri/line-chart-fill";
import pieChartFill from "@iconify-icons/ri/pie-chart-fill";
import qrCodeLine from "@iconify-icons/ri/qr-code-line";

addIcon("arrowRightSLine", ArrowRightSLine);
addIcon("arrowLeftSLine", ArrowLeftSLine);
addIcon("logoutCircleRLine", LogoutCircleRLine);
addIcon("nodeTree", NodeTree);
addIcon("ubuntuFill", UbuntuFill);
addIcon("questionLine", QuestionLine);
addIcon("checkboxCircleLine", CheckboxCircleLine);
addIcon("informationLine", InformationLine);
addIcon("closeCircleLine", CloseCircleLine);
addIcon("arrowUpLine", ArrowUpLine);
addIcon("arrowDownLine", ArrowDownLine);
addIcon("bookmark2Line", Bookmark2Line);
addIcon("add", AddFill);
addIcon("listCheck", ListCheck);
addIcon("more2Fill", More2Fill);
addIcon("database", Database);
addIcon("dict", Dict);
addIcon("card", Card);
addIcon("reset", Reset);
addIcon("dept", Dept);
addIcon("password", Password);
addIcon("ppt", Ppt);
addIcon("terminalWindowLine", TerminalWindowLine);
addIcon("user", User);
addIcon("lock", Lock);
addIcon("userSettingsFill", userSettingsFill);
addIcon("baseStationFill", baseStationFill);
addIcon("barricadeLine", barricadeLine);
addIcon("menuUnfoldFill", menuUnfoldFill);
addIcon("line-chart-fill", lineChartFill);
addIcon("pie-chart-fill", pieChartFill);
addIcon("qrCodeLine", qrCodeLine);
